// panel/frontend/src/views/Login.vue
<template>
  <div class="login-wrap">
    <!-- 背景装饰: 低对比网格 + 光晕, 纯 CSS, 不抢焦点 -->
    <div class="bg-grid" aria-hidden="true"></div>
    <div class="bg-glow" aria-hidden="true"></div>

    <div class="login-card">
      <div class="brand">
        <div class="brand-mark" aria-hidden="true">
          <el-icon :size="26"><Monitor /></el-icon>
        </div>
        <div class="brand-text">
          <h1 class="brand-title">幻兽帕鲁</h1>
          <p class="brand-sub">服务器管理面板</p>
        </div>
      </div>

      <el-form class="form" @submit.prevent="onLogin">
        <el-form-item>
          <el-input v-model="username" placeholder="用户名" size="large"
                    :prefix-icon="User" autocomplete="username" />
        </el-form-item>
        <el-form-item>
          <el-input v-model="password" type="password" placeholder="密码" size="large"
                    :prefix-icon="Lock" show-password autocomplete="current-password"
                    @keyup.enter="onLogin" />
        </el-form-item>
        <el-button type="primary" size="large" :loading="loading" class="btn" @click="onLogin">
          {{ loading ? '登录中…' : '登 录' }}
        </el-button>
      </el-form>

      <p class="foot">Palworld Dedicated Server · Web Console</p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { User, Lock, Monitor } from '@element-plus/icons-vue'
import api from '../api'

const router = useRouter()
const username = ref('admin')
const password = ref('')
const loading = ref(false)

async function onLogin() {
  loading.value = true
  try {
    const form = new URLSearchParams()
    form.append('username', username.value)
    form.append('password', password.value)
    const { data } = await api.post('/api/auth/login', form)
    localStorage.setItem('token', data.access_token)
    router.push({ name: 'dashboard' })
  } catch (e) {
    ElMessage.error(e.response?.data?.detail || '登录失败')
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-wrap {
  position: relative;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--pal-bg);
  overflow: hidden;
}

/* 低对比网格背景 (数据仪表盘观感, 不干扰阅读) */
.bg-grid {
  position: absolute; inset: 0;
  background-image:
    linear-gradient(var(--pal-border-soft) 1px, transparent 1px),
    linear-gradient(90deg, var(--pal-border-soft) 1px, transparent 1px);
  background-size: 40px 40px;
  opacity: .35;
  mask-image: radial-gradient(ellipse 80% 60% at 50% 40%, #000 40%, transparent 100%);
}
/* 强调绿光晕 */
.bg-glow {
  position: absolute; top: 18%; left: 50%;
  width: 520px; height: 520px; transform: translateX(-50%);
  background: radial-gradient(circle, var(--pal-accent-soft) 0%, transparent 70%);
  pointer-events: none;
}

.login-card {
  position: relative;
  width: 380px;
  max-width: calc(100vw - 32px);
  padding: 32px 28px 24px;
  background: var(--pal-surface);
  border: 1px solid var(--pal-border);
  border-radius: var(--pal-radius);
  box-shadow: var(--pal-shadow);
}

.brand { display: flex; align-items: center; gap: 12px; margin-bottom: 28px; }
.brand-mark {
  display: grid; place-items: center;
  width: 48px; height: 48px; border-radius: var(--pal-radius-sm);
  background: var(--pal-accent-soft);
  color: var(--pal-accent);
  border: 1px solid rgba(34, 197, 94, .35);
}
.brand-title { margin: 0; font-size: 20px; font-weight: 700; color: var(--pal-text); letter-spacing: .5px; }
.brand-sub { margin: 2px 0 0; font-size: 13px; color: var(--pal-text-muted); }

.form { margin-top: 4px; }
.btn { width: 100%; font-weight: 600; letter-spacing: 2px; }

.foot {
  margin: 20px 0 0; text-align: center;
  font-family: var(--pal-font-mono);
  font-size: 11px; color: var(--pal-text-faint); letter-spacing: .3px;
}
</style>

// panel/web/src/app/login/page.tsx
'use client'

/**
 * 登录页。
 * - React Hook Form + Zod 校验, 错误就近显示。
 * - 已登录用户重定向到 /dashboard (避免回退到登录页)。
 * - 装饰性网格 + 光晕背景, 纯 CSS, aria-hidden 不干扰读屏。
 */
import { useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { MonitorCog, User, Lock, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useLogin } from '@/features/auth/hooks/use-auth'
import { useAuthStore } from '@/stores/auth-store'

const schema = z.object({
  username: z.string().min(1, '请输入用户名'),
  password: z.string().min(1, '请输入密码'),
})
type FormValues = z.infer<typeof schema>

export default function LoginPage() {
  const router = useRouter()
  const login = useLogin()

  useEffect(() => {
    useAuthStore.getState().hydrate()
    if (useAuthStore.getState().isAuthenticated) router.replace('/dashboard')
  }, [router])

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: { username: 'admin', password: '' },
  })

  function onSubmit(values: FormValues) {
    login.mutate(values)
  }

  return (
    <div className="relative flex min-h-dvh items-center justify-center overflow-hidden bg-background px-4">
      {/* 装饰背景 */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 opacity-[0.4] [mask-image:radial-gradient(ellipse_70%_60%_at_50%_35%,#000_40%,transparent_100%)]"
        style={{
          backgroundImage:
            'linear-gradient(var(--border) 1px, transparent 1px), linear-gradient(90deg, var(--border) 1px, transparent 1px)',
          backgroundSize: '40px 40px',
        }}
      />
      <div
        aria-hidden
        className="pointer-events-none absolute left-1/2 top-[15%] h-[480px] w-[480px] -translate-x-1/2 rounded-full bg-primary/15 blur-3xl"
      />

      <div className="relative w-full max-w-sm">
        <div className="mb-6 flex items-center gap-3">
          <div className="flex size-12 items-center justify-center rounded-xl bg-primary/10 text-primary ring-1 ring-primary/20">
            <MonitorCog className="size-6" />
          </div>
          <div>
            <h1 className="text-lg font-bold tracking-tight">幻兽帕鲁</h1>
            <p className="text-sm text-muted-foreground">服务器管理面板</p>
          </div>
        </div>

        <div className="rounded-2xl border border-border bg-card p-6 shadow-lg">
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4" noValidate>
            <div className="space-y-2">
              <Label htmlFor="username">用户名</Label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  id="username"
                  className="pl-9"
                  autoComplete="username"
                  aria-invalid={!!errors.username}
                  {...register('username')}
                />
              </div>
              {errors.username ? (
                <p className="text-xs text-destructive" role="alert">
                  {errors.username.message}
                </p>
              ) : null}
            </div>

            <div className="space-y-2">
              <Label htmlFor="password">密码</Label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  id="password"
                  type="password"
                  className="pl-9"
                  autoComplete="current-password"
                  aria-invalid={!!errors.password}
                  {...register('password')}
                />
              </div>
              {errors.password ? (
                <p className="text-xs text-destructive" role="alert">
                  {errors.password.message}
                </p>
              ) : null}
            </div>

            <Button type="submit" className="w-full" size="lg" disabled={login.isPending}>
              {login.isPending ? (
                <>
                  <Loader2 className="size-4 animate-spin" />
                  登录中…
                </>
              ) : (
                '登录'
              )}
            </Button>
          </form>
        </div>

        <p className="mt-5 text-center font-mono text-xs text-muted-foreground">
          Palworld Dedicated Server · Web Console
        </p>
      </div>
    </div>
  )
}
